services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: ddbj-search-elasticsearch
    environment:
      TZ: "Asia/Tokyo"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
      http.cors.allow-origin: '"*"'
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD:-ddbj-search-elasticsearch-password}"
    volumes:
      - ${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ${PWD}/elasticsearch/data:/usr/share/elasticsearch/data:rw
      - ${PWD}/elasticsearch/logs:/usr/share/elasticsearch/logs:rw
      - ${PWD}/elasticsearch/backup:/usr/share/elasticsearch/backup:rw
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    mem_limit: 128g
    pids_limit: -1
    networks:
      - ddbj-search-network
    userns_mode: "keep-id:uid=1000,gid=1000"

networks:
  ddbj-search-network:
    name: ddbj-search-network
    external: true
