services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: ddbj-search-converter-dev
    container_name: ddbj-search-converter-dev
    volumes:
      - ${PWD}:/app
      - ${PWD}/converter_results:/app/converter_results
      # 遺伝研スパコン内の resouce
      - /lustre9/open/shared_data/dblink:/lustre9/open/shared_data/dblink:ro
    restart: on-failure
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - ddbj-search-network-dev

networks:
  ddbj-search-network-dev:
    name: ddbj-search-network-dev
    external: true
