services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ddbj-search-converter-dev
    container_name: ddbj-search-converter-dev
    volumes:
      - ${PWD}:/app
      - ${PWD}:/ddbj_search_converter_results:/app/ddbj_search_converter_results:rw
      # 遺伝研スパコン内の resource
      - /lustre9/open/archive/tape/ddbj-dbt/bp-public/bioproject:/lustre9/open/archive/tape/ddbj-dbt/bp-public/bioproject:ro
      - /lustre9/open/archive/tape/ddbj-dbt/bs-public/biosample:/lustre9/open/archive/tape/ddbj-dbt/bs-public/biosample:ro
      - /lustre9/open/shared_data/dblink:/lustre9/open/shared_data/dblink:ro
      - /lustre9/open/database/ddbj-dbt/dra-private/mirror/SRA_Accessions:/lustre9/open/database/ddbj-dbt/dra-private/mirror/SRA_Accessions:ro
      - /lustre9/open/shared_data/dra:/lustre9/open/shared_data/dra:ro
      - /lustre9/open/shared_data/jga/metadata-history/metadata:/lustre9/open/shared_data/jga/metadata-history/metadata:ro
    environment:
      TZ: "Asia/Tokyo"
      DDBJ_SEARCH_CONVERTER_DEBUG: "true"
      DDBJ_SEARCH_CONVERTER_WORK_DIR: "/app/ddbj_search_converter_results"
      DDBJ_SEARCH_CONVERTER_POSTGRES_URL: "postgresql://guestuser:guestuser@a011:54306"
      DDBJ_SEARCH_CONVERTER_ES_URL: "http://ddbj-search-elasticsearch:9200"
      DDBJ_SEARCH_CONVERTER_DBLINK_BASE_PATH: "/lustre9/open/shared_data/dblink"
      DDBJ_SEARCH_CONVERTER_SRA_ACCESSIONS_TAB_BASE_PATH: "/lustre9/open/database/ddbj-dbt/dra-private/mirror/SRA_Accessions"
      DDBJ_SEARCH_CONVERTER_DRA_BASE_PATH: "/lustre9/open/shared_data/dra"
      DDBJ_SEARCH_CONVERTER_JGA_BASE_PATH: "/lustre9/open/shared_data/jga/metadata-history/metadata"
    working_dir: /app
    command: [ "sleep", "infinity" ]
    networks:
      - ddbj-search-network
    init: true

networks:
  ddbj-search-network:
    name: ddbj-search-network
    external: true
