services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ddbj-search-converter-dev
    container_name: ddbj-search-converter-dev
    volumes:
      # ソースコードのマウント (開発用)
      - .:/app:rw
      # 結果出力先
      - ./ddbj_search_converter_results:/app/ddbj_search_converter_results:rw
      # === fixtures を本番と同じパスにマウント ===
      # const
      - ./tests/fixtures/home/w3ddbjld/const:/home/w3ddbjld/const:ro
      # SRA / DRA Accessions
      - ./tests/fixtures/lustre9/open/database/ddbj-dbt/dra-private/mirror/SRA_Accessions:/lustre9/open/database/ddbj-dbt/dra-private/mirror/SRA_Accessions:ro
      - ./tests/fixtures/lustre9/open/database/ddbj-dbt/dra-private/tracesys/batch/logs/livelist/ReleaseData/public:/lustre9/open/database/ddbj-dbt/dra-private/tracesys/batch/logs/livelist/ReleaseData/public:ro
      # DBLink 生成物 (書き込み可能)
      - ./tests/fixtures/usr/local/shared_data/dblink:/usr/local/shared_data/dblink:rw
      # 各種リソース
      - ./tests/fixtures/usr/local/resources/bioproject:/usr/local/resources/bioproject:ro
      - ./tests/fixtures/usr/local/resources/biosample:/usr/local/resources/biosample:ro
      - ./tests/fixtures/usr/local/resources/dra:/usr/local/resources/dra:ro
      - ./tests/fixtures/usr/local/shared_data/jga/metadata-history/metadata:/usr/local/shared_data/jga/metadata-history/metadata:ro
      - ./tests/fixtures/usr/local/resources/trad:/usr/local/resources/trad:ro
      - ./tests/fixtures/usr/local/resources/gea/experiment:/usr/local/resources/gea/experiment:ro
      - ./tests/fixtures/usr/local/shared_data/metabobank/study:/usr/local/shared_data/metabobank/study:ro
    environment:
      DDBJ_SEARCH_CONVERTER_RESULT_DIR: "/app/ddbj_search_converter_results"
      DDBJ_SEARCH_CONVERTER_CONST_DIR: "/home/w3ddbjld/const"
      DDBJ_SEARCH_CONVERTER_ES_URL: "http://elasticsearch:9200"
    working_dir: /app
    command: [ "sleep", "infinity" ]
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - dev-network
    init: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: ddbj-search-es-dev
    environment:
      TZ: "Asia/Tokyo"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es-dev-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  es-dev-data:
    driver: local
